# syntax=docker/dockerfile:1.7-labs
# use buildkit

FROM nvcr.io/nvidia/l4t-jetpack:r36.4.0

# This docker installs:
    # - onedl-mim
    # - onedl-mmcv and onedl-mmengine
    # - ppl.cv
    # - onedl-mmdeploy [cuda;cpu, ort;trt, mmpretrain;mmseg;mmdet;mmrotate]

ARG PPLCV_VERSION=0.8.0

ARG MMCV_VERSION=">=2.3.0"
ARG MMENGINE_VERSION=">=0.10.8"

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_BREAK_SYSTEM_PACKAGES=1

# and install libs
ADD https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/arm64/cuda-keyring_1.1-1_all.deb .
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked,id=apt-cache \
    --mount=type=cache,target=/var/lib/apt,sharing=locked,id=apt-lib \
    dpkg -i cuda-keyring_1.1-1_all.deb && apt-get update \
    && apt-get install -y --no-install-recommends \
    git python3-pip libopenmpi-dev libopenblas-dev libomp-dev libcusparselt0 libcusparselt-dev \
    curl libspdlog-dev vim pkg-config cmake cudss

# install torch, torchvision, onnx
# https://pypi.jetson-ai-lab.dev/
# TODO: copy to our own servers?
RUN --mount=type=cache,target=/root/.cache/pip,id=pip \
    python3 -m pip install --upgrade pip; python3 -m pip install --no-cache \
    https://pypi.jetson-ai-lab.io/jp6/cu126/+f/46b/b8b13f844b211/torch-2.11.0-cp310-cp310-linux_aarch64.whl#sha256=46bb8b13f844b2111f6f41abc703d01075a7185e0c587cb002e957ede2b8c8a3 \
    https://pypi.jetson-ai-lab.io/jp6/cu126/+f/d11/6f08d3d62417d/torchvision-0.26.0-cp310-cp310-linux_aarch64.whl#sha256=d116f08d3d62417dc36cbf41923e491b8b49b77399575f0878ae391e6e77a159 \
    https://pypi.jetson-ai-lab.io/jp6/cu126/+f/d98/0b934b9a29c1a/onnxruntime_gpu-1.24.0-cp310-cp310-linux_aarch64.whl#sha256=d980b934b9a29c1a9d6f39751edd7662b69fadd75556a10ff363773a58ce0950

# install and build pplc.cv
WORKDIR /workspace
RUN git clone -b v${PPLCV_VERSION} --single-branch https://github.com/VBTI-development/ppl.cv.git &&\
    cd ppl.cv &&\
    ./build.sh cuda
ENV PPLCV_DIR=/workspace/ppl.cv

WORKDIR /workspace
# install onedl-mmcv
RUN --mount=type=cache,target=/root/.cache/pip,id=pip \
    python3 -m pip install --no-cache "onedl-mmcv${MMCV_VERSION}" "onedl-mmengine${MMENGINE_VERSION}"  --only-binary=onedl-mmcv -f https://mmwheels.onedl.ai/jetpack61-torch2110/simple/onedl-mmcv &&\
    python3 -m pip install onedl-mim

# ### install mmdeploy
ENV TENSORRT_DIR=/workspace/tensorrt
WORKDIR /workspace/

ENV BACKUP_LD_LIBRARY_PATH=$LD_LIBRARY_PATH
ENV LD_LIBRARY_PATH=/usr/local/cuda/compat/lib.real/:$LD_LIBRARY_PATH

COPY . /workspace/onedl-mmdeploy
RUN cd onedl-mmdeploy && \
    mkdir -p build && cd build &&\
    cmake .. \
        -DMMDEPLOY_BUILD_SDK=ON \
        -DMMDEPLOY_BUILD_SDK_PYTHON_API=ON \
        -DMMDEPLOY_BUILD_EXAMPLES=OFF \
        -DMMDEPLOY_TARGET_DEVICES="cuda;cpu" \
        -DMMDEPLOY_TARGET_BACKENDS="trt" \
        -DMMDEPLOY_CODEBASES="mmpretrain;mmdet;mmseg;mmrotate" \
        -Dpplcv_DIR=${PPLCV_DIR}/cuda-build/install/lib/cmake/ppl &&\
    make -j$(nproc) && make install &&\
    export SPDLOG_LEVEL=debug &&\
    echo "Built MMDeploy version for Jetpack 6.1 devices successfully!" && \
    cd ../ &&\
    python3 -m mim install --config-settings editable_mode=compat -e .

LABEL org.opencontainers.image.source=https://github.com/vbti-development/onedl-mmdeploy
LABEL org.opencontainers.image.description="OneDL MMDeploy Docker Image with Jetpack 6.1 support"
LABEL org.opencontainers.image.licenses=Apache-2.0
LABEL org.opencontainers.image.vendor="VBTI Products BV"
